### ISSUE TITLE
Eldar melee weapons

### ISSUE THREAD

**Issue by Tuco-Ice** [Ogliss/AdMechArmoury#7]
Hello, hope this is the intended procedure for reporting bugs.

The following Eldar Melee weapons are bugged in CE:

Diresword
Miststave
Harlequin's kiss
Dual Ghost Swords
Ghost Axe
Executioner
Singing Spear
Witchblade

They have no damage, no sharp or blunt armor penetration. I've been going through the .xml files in the CESpecific\Patches\ThingDefs_Misc\Weapons folder and comparing these weapons to other working weapons and I can't find anything different in the code. Note however that I'm not a coder, just seeing if the letters match 😄 

Regarding armor stats
The armours don't have any bonus to carrying capacity or to bulk. Wearing them while holding the sweet sweet destructive weapons of this mods bogs the pawns down to a crawl. In CE power armours give bonus to carrying/bulk to allow pawns to hold more ammo and bigger guns. 

Final note:
I have Adeptus Armoury, Xenobiologis and the three playable races (Ork/Eldar/Tau) installed. Also, I don't expect these things to be fixed, I know you're busy with a lot of things, just wanted to let you know. Thanks again for your wonderful work!

**Comment by Ogliss** [comment]
![image](https://user-images.githubusercontent.com/10379205/105408217-9435d280-5c26-11eb-9ea3-d7144fbb63ff.png)
Diresword seems functional

![image](https://user-images.githubusercontent.com/10379205/105408072-68b2e800-5c26-11eb-90bd-10d161c448a2.png)
Mist stave also

![image](https://user-images.githubusercontent.com/10379205/105408387-ccd5ac00-5c26-11eb-9dd0-64bab9439577.png)
Harlequin's kiss

![image](https://user-images.githubusercontent.com/10379205/105408632-1e7e3680-5c27-11eb-9238-2fe6e3e6d6be.png)
Ghost Axe 

![image](https://user-images.githubusercontent.com/10379205/105408494-f2fb4c00-5c26-11eb-9d09-cf89d8033501.png)
Executioner likewise seems functional

Singing Spear is bugged on my end

![image](https://user-images.githubusercontent.com/10379205/105408831-64d39580-5c27-11eb-90f6-a71b034590ae.png)
witchblade seems functional this end, though the reported stats likely arent accurate for them, as their damage scales with the psychic might of the wielder(this also appeals to singing spears)

It could be that i fixed some of these recently and it hasnt made it to steam yet

re the armour, is the carryweight the only issue? or is the armour value out of whack aswell?

**Comment by Ogliss** [comment]
![image](https://user-images.githubusercontent.com/10379205/105411051-c6493380-5c2a-11eb-8260-1afab297b488.png)
singing spear Hopefully fully functional for next update

**Comment by Tuco-Ice** [comment]
Hmm ok. I'll try and download this github version and see if I get the same stats. I just have the version from Steam.

The armour values depend really. I have to say I don't have in depth knowledge of WH40K but I'd think the armour of Imperials and Eldars would be on par with vanilla power armour or even better. Recon armour has 16 sharp (mmRHA), Power armour has 20 and Cataphract 28. Both the Eldar and Imperial armours are worse than recon in regards to protection. I changed the .xml to put the armour values between power armour and cataphract. But I don't know if Scorpion armour is better than Dire Avenger armour so I just made up some numbers between 20 and 28 😃 

Regarding the carry capacity things I messed around with some other mods and added this to Armour_Eldar.xml in the CE patch folder. This gives them around the same carrying/bulk capacity as vanilla power armour in CE:

			<li Class="PatchOperationAdd">
			  <xpath>/Defs/ThingDef[defName="OGE_Apparel_MeshArmour"]/equippedStatOffsets</xpath>
			  <value>
				  <CarryWeight>60</CarryWeight>
				  <CarryBulk>10</CarryBulk>
			  </value>
			</li>

**Comment by Ogliss** [comment]
That Really depends on the armour in question, currently for Vanilla in terms of Sharp protection, imperial flak armour is slightly better than Vanilla flak gear, with carapace armour being a little better than Vanilla scout armour, with the other armour values being the same as sharp, unlike vanilla where sharp is Much higher than the other usually.

its a little tricky to translate, but in table top(at least the editions i played, which i use a general guide), Eldar Mesh and Ranger(Althought this also improves Cover saves in tabletop) armour is on par with Imperial flak (5+ save), Dire Avenger, Howling Banshee, Fire Dragon and Swooping Hawk armour is on par with Imperial Carapace Armour (4+ Save), Striking Scorpion, Dark Reaper and Warp Spider (along with all Exarch variant) armour are on par with Imperial Power armour (3+ Save) and Pheonix Lord armour being roughly on par with Imperial Terminator armour (2+ Save).

Warlocks and Farseer armour is a special case in tabletop, since instead of rolling a D6 for saving like the others, the wearer has to pass a leadership test, rolling less than 8 and 10 respectivly on 2 D6 ,(Lorwise, the provided protection isnt from the physical properties of the armour, but the channeling of the psychic power of the wearer into a sort of force field/shield)

obviously you cant translate it directly, but i try to use it as a kind of scale

Lorewise, as a general rule, Eldar gear is lighter, less bulky hardly encumbers its wearer at all, as its made of a psycho reactive substance that moulds itself perfectly to its wearer, however Unlike power armour, it doesnt increase the wearers strenght or carrying capacity(except for perhaps Dark Reaper armour, which has some sort of advanced stabalization system built into it)

**Comment by Tuco-Ice** [comment]
Ah ok. So Eldar armour should be sleek and fast. I'll reduce the carrying capacity then. 

Also I replaced the OG_AMA_Weapons_Eldar_Melee.xml and Weapons_Eldar_Melee.xml in \1.1\Defs\ThingDefs and \CESpecific\Patches\ThingDefs_Misc\Weapons respectively with the files from this github repo (is that what this is called?). I still don't get the CE stats and the error log throws this:

Trying to get stat MeleeArmorPenetration from OGE_Melee_Diresword which has no support for Combat Extended.

I've checked if the references in the CE patch are off but they seem to point in the right direction. It does say though:

<xpath>Defs/ThingDef

While the path on the drive is \defs\ThingsdefS (ends with an S) but don't know if that matters. But could I be replacing the wrong files?

**Comment by Ogliss** [comment]
Yeah, basicaly eldar and dark eldar are more about mobility and avoiding damage, rather than trying to tank through, might also need to reduce the mass of their weapons, since they would also be lighter than the counterparts of other races

aye yeah, this is a repo.
mixing and matching files like that is ill advised, theres some large differences between versions that could cause issues.

the Path in the patches is a little misleadingly named, its not refering to the filepath, Defs/Thindef[defName="X"] is telling it to search the Defs database for a ThingDef named X, no relation to where its stored on the disk, as the game combines all the XML into one large database for ease of access.

**Comment by Tuco-Ice** [comment]
Ok, I'll replace the entire mod with the version from this repo, see if that works 😄

**Comment by Ogliss** [comment]
haha, gimme a couple mins to fix something then i will push updates to all of them, atm you will probobly have issues since im in between releases and working on functionality for the dark eldar

**Comment by Tuco-Ice** [comment]
Hahaha ok ok. Thanks for all your help by that way ❤️

**Comment by Ogliss** [comment]
alrighty, can give that a bash and see how it goes

**Comment by Tuco-Ice** [comment]
Will do! I'll get right on it

**Comment by Tuco-Ice** [comment]
Ok, did some testing and still doesn't work 😭 

Even with a clean modlist with nothing but HAR, CE and your mods those melee weapons still come up bugged and my Eldars can't craft dark Eldar stuff from the Dark Eldar workbench. I think it's just time I doubled down and learned to code to fix this CE mess (I just love CE too much to not play without it). Where's a good place to learn C# 😆

**Comment by Ogliss** [comment]
and your pulling from the Master branch of the repo right? not the Releases section?

**Comment by Tuco-Ice** [comment]
I think so. I go to https://github.com/Ogliss/AdMechArmoury and the little icon says "Master"

**Comment by Ogliss** [comment]
yeah that should be right, make sure you delete your old local copy when you update them, since files can moved or renamed which can cause issues if you just overwrite the older versions

**Comment by Tuco-Ice** [comment]
Went to where steam workshop keeps the files, deleted everything and then copied the files. I don't think steam overrides them since I made some modifications to the amount of ammo is produced and that doesn't change. Though maybe it's worth a shot to make a local copy in Rimworld directory

**Comment by Ogliss** [comment]
oh yeah, usually best to put github downloads in the local mods folder!

**Comment by Tuco-Ice** [comment]
Haven't bothered you today yet so I figured I'd go ahead and point out that the Tau armours don't have a CE patch 😄 But got the other stuff working with a local copy. Thanks again for the help!

**Comment by Ogliss** [comment]
Glad everything else is working.

ah yeah, havent gotten to the tau apparel yet, only so much patience i have for CE patching, it can be Incredibly frustrating at times :)

**Comment by Ogliss** [comment]
as the weapons issue is resolved, i will close this thread, unless theres anything else?

**Comment by Tuco-Ice** [comment]
We good :D
