### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by Tuco-Ice** [Ogliss/AdMechArmoury#8]
Hey and sorry to bother you on your Star Citizen vacation. Just a quick question if I may.

Is there an easy/quick way to enable production/research of Imperial/Mechanicus tech for other alien races? A nifty .xml copy and paste or something?

**Comment by Ogliss** [comment]
im not sure you can consider it easy/quick, because of the way alien races handles racial restriction the only way to do it would be to add all the recipes/research to whatever relevent restrictioned list for the race you wanted to be able to use it.

because im a forgetful cunt, and always forget to add new items to the relevent races restrictions, i hardcode it to automatically grab all the recipes/research and add them when the game starts up via C#, not way to disabled it without rebuilding the assembly yourself

i do plan to add mod options to allow other races to be added to count as Imperial/Mechanicus (though other 40k races would be ommitted), since people keep asking/complaining about it, but as im i bit of a puritan(i dont ever use any other race mods myself or any that I dont feel like they fit in 40k) and its a pain in the arse setting it up, i'm afraid its not a very high priority for me.

**Comment by Tuco-Ice** [comment]
Fair enough. But forgetful cunts are the best cunts I find <3 Thanks for the quick response!
